package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeFixture 将合成源码写入隔离的测试目录。
func writeFixture(t *testing.T, root, name, source string) string {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// TestCheckAcceptsDocumentedCode 验证集中包说明、方法、分组类型、局部类型和匿名函数。
func TestCheckAcceptsDocumentedCode(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "doc.go", "// Package sample 提供测试功能。\npackage sample\n")
	writeFixture(t, root, "sample.go", `package sample
// Worker 处理一个任务。
type Worker struct{}
// Run 执行任务。
func (Worker) Run() { callback := func() {}; callback() }
type (
 // Port 表示端口。
 Port int
 // Runner 声明运行接口。
 Runner interface { Run() }
)
// Alias 表示别名。
type Alias = Port
// 单项分组也可以使用声明级说明。
type ( ID string )
var ignored = 1
// Build 使用局部类型。
func Build() {
 // state 记录局部状态。
 type state struct{}
 _ = state{}
}
`)
	writeFixture(t, root, "sample_test.go", "package sample\n// TestExample 验证行为。\nfunc TestExample() {}\n")
	diagnostics, files, err := check(root)
	if err != nil || len(diagnostics) != 0 || files != 3 {
		t.Fatalf("check = %#v, %d, %v", diagnostics, files, err)
	}
}

// TestCheckReportsMissingChinese 验证英文或无汉字注释、缺失注释、方法、局部类型以及多项声明逐项报错。
func TestCheckReportsMissingChinese(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "bad.go", `// Package sample is undocumented in Chinese.
package sample
// Worker processes jobs.
type Worker struct{}
type Runner interface { Run() }
// 此分组说明不能代替各类型的说明。
type ( First int; Second string )
// Run processes a job.
func Run() {}
func hidden() {}
func (Worker) Stop() {}
// Loop — runs forever…
func Loop() {}
// Build 构建局部状态。
func Build() { type localState struct{ n int }; _ = localState{} }
`)
	writeFixture(t, root, "bad_test.go", "package sample\nfunc TestMissing() {}\n")
	want := []string{
		"包 sample 缺少中文包级文档",
		"类型 Worker 缺少中文文档注释",
		"类型 Runner 缺少中文文档注释",
		"类型 First 缺少中文文档注释",
		"类型 Second 缺少中文文档注释",
		"函数 Run 缺少中文文档注释",
		"函数 hidden 缺少中文文档注释",
		"函数 Stop 缺少中文文档注释",
		"函数 Loop 缺少中文文档注释",
		"类型 localState 缺少中文文档注释",
		"函数 TestMissing 缺少中文文档注释",
	}
	diagnostics, files, err := check(root)
	if err != nil || files != 2 || len(diagnostics) != len(want) {
		t.Fatalf("check = %#v, %d, %v", diagnostics, files, err)
	}
	for i, item := range diagnostics {
		if item.Position.Line <= 0 || item.Message != want[i] {
			t.Fatalf("诊断 %d = %#v，期望 %q", i, item, want[i])
		}
	}
}

// TestCheckGeneratedAndExcluded 验证标准生成文件和 go 工具忽略的目录豁免，但非标准生成标记和正常测试源码不会豁免。
func TestCheckGeneratedAndExcluded(t *testing.T) {
	root := t.TempDir()
	for _, directory := range []string{".git", ".local", ".cache", ".hg", ".svn", ".claude/worktrees/x", "_old", "vendor", "testdata"} {
		writeFixture(t, root, directory+"/bad.go", "invalid syntax")
	}
	writeFixture(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage sample\nfunc Generated() {}\n")
	writeFixture(t, root, "fake.go", "package sample\n// Helper wraps things. DO NOT EDIT.\nfunc Helper() {}\n")
	writeFixture(t, root, "handwritten.go", "// Code generated by hand.\npackage sample\nfunc Handwritten() {}\n")
	writeFixture(t, root, "plain.txt", "not Go")
	writeFixture(t, root, "real.go", "// Package sample 中文说明。\npackage sample\n")
	writeFixture(t, root, "real_test.go", "package sample\nfunc TestMissing() {}\n")
	want := []string{"Helper", "Handwritten", "TestMissing"}
	diagnostics, files, err := check(root)
	if err != nil || files != 4 || len(diagnostics) != len(want) {
		t.Fatalf("check = %#v, %d, %v", diagnostics, files, err)
	}
	for i, name := range want {
		if !strings.Contains(diagnostics[i].Message, name) {
			t.Fatalf("诊断 %d = %#v，期望包含 %q", i, diagnostics[i], name)
		}
	}
}

// TestCheckPackageDocsPreferNonTestFiles 验证包说明须来自非测试文件，只有测试文件的包仍由测试文件提供说明。
func TestCheckPackageDocsPreferNonTestFiles(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "inner/a_test.go", "// Package p 只写在测试文件里的包说明。\npackage p\n")
	source := writeFixture(t, root, "inner/b.go", "package p\n")
	writeFixture(t, root, "outer/doc.go", "// Package q 中文说明。\npackage q\n")
	writeFixture(t, root, "outer/external_test.go", "// Package q_test 外部测试包的中文说明。\npackage q_test\n")
	diagnostics, files, err := check(root)
	if err != nil || files != 4 || len(diagnostics) != 1 ||
		diagnostics[0].Position.Filename != source || diagnostics[0].Message != "包 p 缺少中文包级文档" {
		t.Fatalf("check = %#v, %d, %v", diagnostics, files, err)
	}
}

// TestCheckPackageIsolation 验证包说明不会泄漏到另一目录或外部测试包。
func TestCheckPackageIsolation(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "doc.go", "// Package sample 中文说明。\npackage sample\n")
	writeFixture(t, root, "external_test.go", "package sample_test\n")
	writeFixture(t, root, "child/child.go", "package sample\n")
	diagnostics, _, err := check(root)
	if err != nil || len(diagnostics) != 2 {
		t.Fatalf("check = %#v, %v", diagnostics, err)
	}
}

// TestCheckRejectsInvalidRootAndSyntax 验证不存在路径、文件路径与语法错误都失败。
func TestCheckRejectsInvalidRootAndSyntax(t *testing.T) {
	root := t.TempDir()
	path := writeFixture(t, root, "bad.go", "invalid syntax")
	for _, target := range []string{root + "/missing", path, root} {
		if _, _, err := check(target); err == nil {
			t.Errorf("期望 %q 失败", target)
		}
	}
}

// TestCheckRejectsSymlinkedGoFiles 验证符号链接形式的 Go 源码直接报错，其他符号链接不被跟随，
// go 工具忽略的「.」「_」开头文件（如悬空的编辑器锁文件）不报错。
func TestCheckRejectsSymlinkedGoFiles(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	source := writeFixture(t, outside, "bad.go", "package sample\nfunc Missing() {}\n")
	if err := os.Symlink(outside, filepath.Join(root, "linked")); err != nil {
		t.Skipf("当前平台不能创建符号链接: %v", err)
	}
	writeFixture(t, root, "doc.go", "// Package sample 中文说明。\npackage sample\n")
	for _, name := range []string{".#doc.go", "_backup.go"} {
		if err := os.Symlink(filepath.Join(root, "missing-target"), filepath.Join(root, name)); err != nil {
			t.Fatal(err)
		}
	}
	diagnostics, files, err := check(root)
	if err != nil || len(diagnostics) != 0 || files != 1 {
		t.Fatalf("check = %#v, %d, %v", diagnostics, files, err)
	}
	if err := os.Symlink(source, filepath.Join(root, "linked.go")); err != nil {
		t.Fatal(err)
	}
	if _, _, err := check(root); err == nil || !strings.Contains(err.Error(), "符号链接") {
		t.Fatalf("check error = %v，期望拒绝符号链接形式的 Go 源码", err)
	}
}

// TestRun 验证检查器退出码以及供人阅读的输出。
func TestRun(t *testing.T) {
	good := t.TempDir()
	writeFixture(t, good, "doc.go", "// Package good 中文说明。\npackage good\n")
	bad := t.TempDir()
	writeFixture(t, bad, "bad.go", "package bad\nfunc Missing() {}\n")
	empty := t.TempDir()
	cases := []struct {
		name string
		args []string
		code int
		text string
	}{
		{"pass", []string{good}, 0, "通过"},
		{"missing comments", []string{bad}, 1, "Missing"},
		{"missing root", []string{good + "/missing"}, 1, "commentcheck:"},
		{"empty root", []string{empty}, 1, "未找到手写 Go 文件"},
		{"extra args", []string{good, bad}, 2, "用法"},
		{"bad flag", []string{"-unknown"}, 2, "flag provided"},
		{"help", []string{"-h"}, 0, "用法"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var stdout, stderr bytes.Buffer
			if code := run(tc.args, &stdout, &stderr); code != tc.code {
				t.Errorf("退出码 = %d，期望 %d", code, tc.code)
			}
			if !strings.Contains(stdout.String()+stderr.String(), tc.text) {
				t.Errorf("输出缺少 %q: %s%s", tc.text, &stdout, &stderr)
			}
		})
	}
}

// TestRunRejectsSymlinkRoot 验证符号链接根路径不会以零个文件静默通过。
func TestRunRejectsSymlinkRoot(t *testing.T) {
	target := t.TempDir()
	writeFixture(t, target, "bad.go", "package bad\nfunc Missing() {}\n")
	link := filepath.Join(t.TempDir(), "link")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("当前平台不能创建符号链接: %v", err)
	}
	var stdout, stderr bytes.Buffer
	if code := run([]string{link}, &stdout, &stderr); code != 1 || !strings.Contains(stderr.String(), "未找到手写 Go 文件") {
		t.Fatalf("退出码 = %d，输出: %s%s", code, &stdout, &stderr)
	}
}

// TestRunDefaultsToCurrentDirectory 验证省略根路径时检查当前包。
func TestRunDefaultsToCurrentDirectory(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run(nil, &stdout, &stderr); code != 0 {
		t.Fatalf("默认目录检查失败: %d %s", code, &stderr)
	}
}
